apiVersion : apps/v1
kind: Deployment
metadata:
  name: azurevotefront 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurevotefront
  template:
    metadata:
      labels:
        app: azurevotefront 
    spec:
      containers:
        - name: azurevotefront 
          image: acrdolly.azurecr.io/azurevotefront
          ports:
          - containerPort: 80