apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: acrdolly.azurecr.io/redis:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azurevotefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurevotefront
  template:
    metadata:
      labels:
        app: azurevotefront
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azurevotefront
        image: acrdolly.azurecr.io/azurevotefront:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
